name: Simple Workflow

env:
  NAME: "foo"
  
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      name:
        default: World
        description: Who are you?

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Welcome by name
        run: echo Hello, ${{ inputs.name || $NAME }} !
