name: CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      name:
        default: World
        description: Who are you?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, ${{inputs.name}}!
